### ISSUE TITLE
[Bug] On IOS simulator - Android is fine - Typing into the Name field on the Create Account page throws Uncaught Error

### ISSUE THREAD

**Issue by gaborfekete85** [creativetimofficial/soft-ui-react-native#19]
### Version
1.0.2
### Reproduction link
https://jsfiddle.net/
### Operating System
IOS 16.1
### Device
iPhone 14 Pro Max Simulator
### Browser & Version
-
### Steps to reproduce
Run the Application on IOS simulator ( iPhone 14 Pro Max )
Open the "Create Account" page
Focus on the Name field
Try to enter something into the field
The RED error screen shows up
### What is expected?
The text can be entered into the field.
### What is actually happening?
Uncaught Error Screen shows up when trying to enter something into the Name field on the "Create Account"page

---
### Solution
X
### Additional comments
The given error:
TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
x: x,
y: y,
animated: animated
})', 'responder.scrollResponderScrollTo' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

TypeError: responder.scrollResponderScrollTo is not a function. (In 'responder.scrollResponderScrollTo({
x: x,
y: y,
animated: animated
})', 'responder.scrollResponderScrollTo' is undefined)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:95:4 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:141:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0

**As You can see it works fine on Android simulator but fails on the IOS simulator.** 

![image](https://user-images.githubusercontent.com/12583202/204140068-4a98d7b6-629a-4b83-8953-7c859dc4b982.png)

**Comment by tsingh-kvd** [comment]
Updating "react-native-keyboard-aware-scroll-view" to "0.9.5" fixed it
